server:
  port: ${SERVER_PORT:8080}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:50051}

spring:
  application:
    name: pulse-ingestion
  kafka:
    bootstrap-servers: 127.0.0.1:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      properties:
        acks: 1             # Leader only (Fast)
        linger.ms: 10       # Wait 10 ms to group messages together
        batch.size: 16384   # 16KB batches
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest  # Read from beginning if no offset exists

# DynamoDB Configuration
dynamodb:
  endpoint: ${DYNAMODB_ENDPOINT:http://localhost:8000}

